# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(verbose_name='event date')),
                ('end_time', models.DateTimeField(null=True, verbose_name='event date')),
                ('facebook_id', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facebook_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('facebook_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
                ('facebook_name', models.CharField(max_length=255)),
                ('facebook_city', models.CharField(max_length=255)),
                ('facebook_country', models.CharField(max_length=255)),
                ('facebook_zip', models.CharField(max_length=255, null=True)),
                ('facebook_street', models.CharField(max_length=255, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='facebookplace',
            index=models.Index(fields=['latitude', 'longitude'], name='events_face_latitud_e053fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facebookplace',
            unique_together=set([('latitude', 'longitude')]),
        ),
        migrations.AddField(
            model_name='facebookevent',
            name='facebook_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.FacebookPlace'),
        ),
        migrations.AddIndex(
            model_name='facebookevent',
            index=models.Index(fields=['start_time', 'end_time'], name='events_face_start_t_d6ada5_idx'),
        ),
    ]
