# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('events', '0001_initial'), ('events', '0002_remove_place_location'), ('events', '0003_auto_20170906_1454'), ('events', '0004_auto_20170906_1455'), ('events', '0005_auto_20170906_1515'), ('events', '0006_auto_20170906_1648'), ('events', '0007_auto_20170908_1415')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
