# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 20:09
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicevent',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
    ]
