# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170908_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookevent',
            name='facebook_place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='events.FacebookPlace'),
            preserve_default=False,
        ),
    ]
