# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_place_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Location',
        ),
    ]
