# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170911_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookplace',
            name='google_administrative_area_level_1',
        ),
        migrations.RemoveField(
            model_name='facebookplace',
            name='google_administrative_area_level_2',
        ),
        migrations.RemoveField(
            model_name='facebookplace',
            name='google_administrative_area_level_3',
        ),
        migrations.RemoveField(
            model_name='facebookplace',
            name='google_country',
        ),
        migrations.RemoveField(
            model_name='facebookplace',
            name='google_formatted_address',
        ),
        migrations.RemoveField(
            model_name='facebookplace',
            name='google_locality',
        ),
        migrations.RemoveField(
            model_name='facebookplace',
            name='google_neighborhood',
        ),
        migrations.RemoveField(
            model_name='facebookplace',
            name='google_sublocality_level_1',
        ),
        migrations.RemoveField(
            model_name='facebookplace',
            name='google_sublocality_level_2',
        ),
        migrations.AddField(
            model_name='facebookplace',
            name='facebook_region',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
