# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_facebookevent_facebook_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookevent',
            name='facebook_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookplace',
            name='facebook_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
