# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:55
from __future__ import unicode_literals

from django.db import migrations
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170906_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='search',
            field=events.models.MockPointField(blank=True, max_length=255),
        ),
    ]
