# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170911_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookevent',
            options={'ordering': ['start_time']},
        ),
    ]
