# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 00:04
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_place_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
        migrations.AddField(
            model_name='place',
            name='location2',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
    ]
