# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170908_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookevent',
            name='facebook_url',
        ),
    ]
