# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170906_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='show',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='events.Location'),
            preserve_default=False,
        ),
    ]
