# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_facebookevent_facebook_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookpage',
            old_name='facebook_url',
            new_name='facebook_id',
        ),
    ]
