# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 13:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20171001_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookplace',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
