# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 00:07
from __future__ import unicode_literals

from django.db import migrations, models
# import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170902_0004'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='PointOfInterest',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=100)),
        #         ('position', geoposition.fields.GeopositionField(max_length=42)),
        #     ],
        # ),
        # migrations.RemoveField(
        #     model_name='place',
        #     name='location2',
        # ),
    ]
