# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170908_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookplace',
            name='facebook_street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facebookplace',
            name='facebook_zip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
