# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 02:44
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170902_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
