# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170908_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookevent',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='event date'),
        ),
    ]
