# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_place_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='city',
            new_name='address',
        ),
    ]
