# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 01:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20171024_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookplace',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
