# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170902_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True),
        ),
    ]
