# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20171024_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookevent',
            name='slug',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
