# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_facebookgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookevent',
            name='image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
