# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170902_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='administrative_area_level_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='administrative_area_level_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='administrative_area_level_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='locality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='sublocality_level_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='sublocality_level_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
