# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:31
from __future__ import unicode_literals

# import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('address', '0001_initial'),
        ('events', '0013_place_name'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Address',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('address1', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
        #     ],
        # ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(help_text='Map will update as you type, other fields update on save', max_length=255),
        ),
    ]
