# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20170905_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='anything',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=location_field.models.plain.PlainLocationField(help_text="Don't touch this", max_length=63, null=True),
        ),
    ]
