# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 23:05
from __future__ import unicode_literals

from django.db import migrations
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20170905_2254'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='address',
        #     name='address1',
        # ),
        migrations.RemoveField(
            model_name='place',
            name='anything',
        ),
        migrations.AddField(
            model_name='place',
            name='arbitrary',
            field=events.models.ArbitraryField(blank=True, max_length=255),
        ),
        # migrations.DeleteModel(
        #     name='Address',
        # ),
    ]
