# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_delete_pointofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
